version: "3"
services:
  node-app:
    # build:
    #   context: C:\MALITH\Development\saloon-app\appointment-service
    #   dockerfile: Dockerfile
    image: appointment-service:latest
    environment:
      - USER=postgres
      - HOST=postgres
      - DATABASE=sms
      - PASSWORD=postgres@123
      - DB_PORT=5432
      - SERVER_PORT=6000
      - JWT_SECRET=VFCiVujQICfu2ZPg
    ports:
      - "6000:6000"
    depends_on:
      - postgres
    networks:
      - my-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
      POSTGRES_DB: sms
    ports:
      - "5432:5432"
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
    networks:
      - my-network

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - ./certs:/etc/letsencrypt
  #     - ./html:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html -d ec2-54-87-254-241.compute-1.amazonaws.com
  #   environment:
  #     - CERTBOT_EMAIL=your@email.com
  #   networks:
  #     - my-network

networks:
  my-network:
